add main-svc
ns1s1/java-explore-with-me pull request #3
Opened 2024-03-17 19:57 UTC by ns1s1

2024-03-18 20:35 UTC, Fleaman777 requested changes

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/request/dto/ParticipationRequestDto.java
> +    private LocalDateTime created;
Для поля created рассмотри возможность автоматической установки времени создания записи путем использовния аннотаций @CreationTimestamp или @CreatedDate.

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/dto/EventFullDto.java
> +    private Boolean paid;
Используй тип boolean для примитивных значений, чтобы избежать ненужной обертки и NullPointerException.

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/dto/NewEventDto.java
> +    private Boolean requestModeration = true;
Установка значения по умолчанию в поле сущности может быть неочевидной; лучше делать это явно в бизнес-логике или конструкторе.

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/model/Event.java
> +    private User initiator;
если ожидается, что поле initiator в логике будет использоваться часто, то FetchType можно было бы сделать Eager

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/user/service/UserServiceImpl.java
> +    public List<UserDto> findAll(List<Long> ids, Integer from, Integer size) {
в теории Integer from, Integer size могут быть null. поэтому лучше в качестве типа делать приметив, что бы избежать NPE

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +    public CategoryDto create(NewCategoryDto newCategoryDto) {
метод изменяет состояние БД, правильней было бы его выполнять в транзакции, 

аналагично в др местах

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/compilation/service/CompilationServiceImpl.java
> +
дело вкуса, но если у полей нет аннотаций, то можно не добавлять пустые строки между ними, что немного улучшает восприятие

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                        "Event c id = " + eventId + " и Userid = " + userId + " не найден"));
можно было бы использовать String.format, что бы вставить значения в строку, для более лучшего восприятия

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/request/service/ParticipationRequestServiceImpl.java
> +    }
получился достаточно длинный метод, хорошо было бы некоторые логические части вынести в отдельные методы

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/request/service/ParticipationRequestServiceImpl.java
> +        return requests.stream()
в целом, можно не создавать переменную reqeusts, а сразу вызывать стрим на participationRequestRepository
                .findAllByEventIdAndEventInitiatorId(eventId, userId)

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/request/service/ParticipationRequestServiceImpl.java
> +        if (!event.getState().equals(EventState.PUBLISHED)) {
енамы хорошо сравнивать через == 
так и сравнивается быстрее, и выглядит чуть очевидней

аналагично в др местах

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/resources/schema.sql
> +    created_on TIMESTAMP NOT NULL,
можно добавить дефолтную установку времени

2024-03-18 20:35 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/event/controller/AdminEventController.java
> +        return eventService.getAdminEvents(users, states, categories, rangeStart, rangeEnd, from, size);
понимаю, это по заданию так, поэтому можно не исправлять,
но если в запросе ожидается много параметров или уже они есть, то более читаемо и удобно использовать пост или патч запрос с боди, в котором будут все эти параметры

2024-03-19 16:05 UTC, ns1s1 commented on main-service/src/main/java/ru/practicum/event/controller/AdminEventController.java
> +        return eventService.getAdminEvents(users, states, categories, rangeStart, rangeEnd, from, size);
Понял проблематику, но не стал менять из-за postman тестов

2024-03-20 18:06 UTC, Fleaman777 approved these changes

2024-03-20 18:14 UTC, merged